### ISSUE TITLE
NodeJS runtime `MODULE_NOT_FOUND` error

### ISSUE THREAD

**Issue by capcom6** [zhelvis/unisender-ts#1]
Hello!

I created an empty NodeJS project with TypeScript, and when I try to import your library, I receive a `MODULE_NOT_FOUND` error at runtime. The library exists in the `node_modules` folder, and TypeScript didn't emit any warnings or errors during transpilation.

Can you help with this error?

P.S. The library works fine with the Bun runtime, but I have to use NodeJS.

Contents of my `tsconfig.json`:

```js
{
  "compilerOptions": {
    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "module": "commonjs",                                /* Specify what module code is generated. */
    "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}
```

**Comment by capcom6** [comment]
I've resolved the initial issue by adding `"main": "dist/index.js"` to the library's `package.json`.

However, another issue has arisen: `ERR_REQUIRE_ESM` when importing your library. The only way I found to resolve this is to remove `"type": "module"` from the `package.json` file and update `tsconfig.json` as follows:

```json
{
  "compilerOptions": {
    "lib": [],
    "target": "ES2016",
    "module": "CommonJS",
    "outDir": "dist",
    "declaration": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": [
    "src"
  ]
}
```

After rebuilding, I can use this library in both NodeJS and Bun.

Is there any other way to make it work with a NodeJS project using the CommonJS module style?

**Comment by capcom6** [comment]
I've found the most straightforward way to import and use the current version of the library: dynamic import, as NodeJS suggests in the error message:

```javascript
const unisender = await import('unisender-ts');
```

This works even without the `main` key in the `package.json`.

I think it would be helpful to add this information to the `README` for other NodeJS users.

Thanks for this library!

**Comment by zhelvis** [comment]
@capcom6 Hi!

> Is there any other way to make it work with a NodeJS project using the CommonJS module style?

gave a detailed reply in the [pr](https://github.com/zhelvis/unisender-ts/pull/2#pullrequestreview-2304264693)

**Comment by zhelvis** [comment]
@capcom6 new version `0.1.0` uploaded to npm:
https://www.npmjs.com/package/unisender-ts
